-- Arul — Neon Postgres schema (5/5: curated All-feed head). Apply after
-- 04_ringtones.sql. Added 2026-08-01.
--
-- feed_rank is the CURATED head of the All feed only, managed by drag-and-drop
-- in the CMS. Rows with a non-null rank sort first by feed_rank ASC (tie → id);
-- everything still null follows in the app's existing stable FNV-1a shuffle
-- (CLAUDE.md §5b, feedOrder() in catalog_providers.dart).
--
-- Deliberately NOT sort_order: that column drives CATEGORY-chip order
-- (build-catalog emits sort_order ASC, created_at DESC, id ASC) and 341 of the
-- 614 live rows carry distinct non-zero values from their import manifests —
-- reusing it would reorder every chip, and this change is scoped to All.
--
-- Nullable with no default and no index, both on purpose: NULL everywhere means
-- the All feed is byte-identical to today until an admin curates, and a curated
-- head of a few dozen rows out of 614 is not worth an index. Ranks are written
-- sparsely (10, 20, 30 …) so a future drag renumbers without cascading.
alter table wallpapers add column if not exists feed_rank integer;
