-- Arul — Neon Postgres schema (retire admin pinning). Apply after 10_apply_score.sql.
--
-- Drops the hand-pinning column from both content tables. The feed orders itself
-- from applies now (10_apply_score.sql, workers/src/lib/feed-score.ts) and NOTHING
-- reads or writes this column any more — build-catalog COMPUTES the rank and emits
-- it into the catalog JSON under the same `feed_rank` name, which is what let merit
-- order reach installs that never update without an app release. The JSON field
-- stays; only the column goes.
--
-- 05_feed_rank.sql and 08_ringtone_feed_rank.sql are DELETED rather than kept
-- beside this file: schema files ARE the migration here, so a fresh database must
-- never create a column the next file drops.
--
-- THE ONE TRAP THOSE FILES PAID FOR, kept because it outlived the feature: curated
-- order must never live in `sort_order`. v1 stored it there, every bulk import
-- reset it, and the curation died silently — which is what retired v1. `sort_order`
-- is the order WITHIN a category and imports own it; nothing else may share it.
-- The same reasoning is why the merit score got its own columns instead of being
-- folded into `apply_count`.
--
-- Safe to run against a database still serving the previous Worker: that build read
-- the column as a nullable pin, and a missing column simply reads as no pins, which
-- degrades to catalog order rather than failing.
alter table wallpapers drop column if exists feed_rank;
alter table ringtones  drop column if exists feed_rank;
