/**
 * The local stack: Arul Worker + local CDN + CMS on this PC, the phone reaching them over `adb reverse`.
 * Debug branch + local R2 only — nothing here reaches production storage. Owner guide: docs/local-stack.md.
 *
 *   node tools/local-stack.mjs up [--no-cms] [--persist-to DIR]   # start all three, adb reverse, health check
 *   node tools/local-stack.mjs status                             # health + adb reverse list
 *   node tools/local-stack.mjs down                               # stop everything `up` started, drop the reverses
 *   node tools/local-stack.mjs env                                # (re)write env/local.json from env/dev.json
 *
 * Ports: Worker 8787 · CDN 8788 · CMS 8790. State, logs and the dev registry live in the persist dir
 * (default C:/Anish/Arul/.wrangler/local-stack, git-ignored). The Worker gets these overrides on top of .dev.vars:
 *   R2_CDN_BASE_URL -> the local CDN · R2_ENDPOINT/R2_BUCKET -> the CDN's /__s3 path, so a presigned URL
 *   resolves against LOCAL R2 · POSTHOG_HOST blackholed · PUSH_ENABLED=false.
 */
import { spawn, spawnSync } from "node:child_process";
import fs from "node:fs";
import net from "node:net";
import path from "node:path";
import { setTimeout as sleep } from "node:timers/promises";
import { parseArgs } from "node:util";
import {
  CDN_DIR,
  CDN_URL,
  CMS_DIR,
  DEBUG_ENDPOINT,
  PORTS,
  REPO_DIR,
  WORKER_ENV_FILE,
  WORKER_URL,
  WORKERS_DIR,
  WRANGLER_JS,
  debugUrl,
  devVar,
  endpointOf,
  persistDir,
  refuse,
  refuseRemoteFlags,
} from "./local-lib.mjs";

refuseRemoteFlags(process.argv.slice(2));
const { values: flags, positionals } = parseArgs({
  allowPositionals: true,
  options: { "persist-to": { type: "string" }, "no-cms": { type: "boolean", default: false } },
});
const cmd = positionals[0];

const PERSIST = persistDir(flags["persist-to"]);
const LOGS = path.join(PERSIST, "logs");
const REGISTRY = path.join(PERSIST, "registry");
const STATE = path.join(PERSIST, "stack.json");
const INSPECTOR = { worker: 9230, cdn: 9231, cms: 9232 };

switch (cmd) {
  case "up":
    await up();
    break;
  case "down":
    down();
    break;
  case "status":
    await status();
    break;
  case "env":
    writeLocalEnv();
    break;
  default:
    console.error("usage: node tools/local-stack.mjs <up|down|status|env> [--no-cms] [--persist-to DIR]");
    process.exit(2);
}

/** env/local.json = env/dev.json with the two hosts swapped for loopback. Values are never printed. */
function writeLocalEnv() {
  const src = path.join(REPO_DIR, "env", "dev.json");
  const dst = path.join(REPO_DIR, "env", "local.json");
  if (!fs.existsSync(src)) refuse("env/dev.json is missing — copy env.example.json and fill it first");
  const cfg = JSON.parse(fs.readFileSync(src, "utf8"));
  cfg._readme =
    "GENERATED by workers/tools/local-stack.mjs env from env/dev.json — do not edit. Points the debug build at the local stack (docs/local-stack.md).";
  cfg.API_BASE_URL = WORKER_URL;
  cfg.R2_CDN_BASE_URL = CDN_URL;
  fs.writeFileSync(dst, JSON.stringify(cfg, null, 2) + "\n");
  console.log(
    `[env] wrote env/local.json (${Object.keys(cfg).length} keys; API_BASE_URL=${WORKER_URL}, R2_CDN_BASE_URL=${CDN_URL})`,
  );
}

async function up() {
  const phonepeEnv = devVar("PHONEPE_ENV");
  if (phonepeEnv !== "SANDBOX")
    refuse(`workers/.dev.vars PHONEPE_ENV must be SANDBOX (found "${phonepeEnv}")`);
  const dbUrl = debugUrl();

  const running = readState();
  if (running && Object.values(running.pids).some(alive)) {
    console.log("[stack] already up (stack.json) — `status` to check, `down` to stop");
    return status();
  }
  const withCms = !flags["no-cms"];
  const wanted = withCms ? PORTS : { worker: PORTS.worker, cdn: PORTS.cdn };
  for (const [name, port] of Object.entries(wanted)) {
    if (await portBusy(port))
      refuse(`port ${port} (${name}) is already in use — stop whatever holds it first`);
  }

  writeLocalEnv();
  fs.mkdirSync(LOGS, { recursive: true });
  fs.mkdirSync(REGISTRY, { recursive: true });
  console.log(`[stack] persist dir ${PERSIST}`);
  console.log(`[stack] debug branch ${endpointOf(dbUrl)} · local R2 · PostHog blackholed · push off`);

  writeWorkerEnv(withCms);
  const pids = {};
  pids.cdn = start("cdn", CDN_DIR, process.execPath, [WRANGLER_JS, ...devArgs(PORTS.cdn, INSPECTOR.cdn)]);
  pids.worker = start(
    "worker",
    WORKERS_DIR,
    process.execPath,
    [
      WRANGLER_JS,
      ...devArgs(PORTS.worker, INSPECTOR.worker),
      "--env-file",
      WORKER_ENV_FILE,
      "--var",
      `R2_CDN_BASE_URL:${CDN_URL}`,
      "--var",
      `R2_ENDPOINT:${CDN_URL}/__s3`,
      "--var",
      "R2_BUCKET:south-indian-wallpapers",
      "--var",
      "POSTHOG_HOST:http://127.0.0.1:9",
      "--var",
      "PUSH_ENABLED:false",
    ],
    { CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE: dbUrl },
  );
  if (withCms) pids.cms = startCms();
  fs.writeFileSync(STATE, JSON.stringify({ pids, started_at: new Date().toISOString() }, null, 2));

  for (const name of Object.keys(pids)) {
    const ok = await waitReady(name);
    console.log(
      `[stack] ${name.padEnd(6)} ${ok ? "ready" : `NOT READY — read ${path.join(LOGS, name + ".log")}`}`,
    );
  }
  adbReverse();
  await status();
}

function devArgs(port, inspector) {
  return [
    "dev",
    "--local",
    "--ip",
    "127.0.0.1",
    "--port",
    String(port),
    "--inspector-port",
    String(inspector),
    "--persist-to",
    PERSIST,
    "--show-interactive-dev-session=false",
  ];
}

/**
 * Prefers the CMS repo's own `dev:local` script (it owns the CMS-side local wiring). Without it, runs plain
 * `wrangler dev --local` on the shared persist dir + registry, with both Hyperdrive strings verified as debug.
 */
function startCms() {
  const pkg = JSON.parse(fs.readFileSync(path.join(CMS_DIR, "package.json"), "utf8"));
  const cmsEnv = readDotenv(path.join(CMS_DIR, ".env"));
  const hd = {};
  for (const b of ["HYPERDRIVE_ARUL", "HYPERDRIVE_PAKIZA"]) {
    const k = `CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_${b}`;
    const v = process.env[k] || cmsEnv[k];
    if (!v)
      refuse(`CMS ${k} is not set (Unified CMS/.env) — start with --no-cms or set it to the debug branch`);
    if (endpointOf(v) !== DEBUG_ENDPOINT) refuse(`CMS ${k} is not the debug branch (${endpointOf(v)})`);
    hd[k] = v;
  }
  if (pkg.scripts?.["dev:local"]) {
    console.log("[stack] cms    via `npm run dev:local` (Unified CMS)");
    return start("cms", CMS_DIR, "npm run dev:local", [], {
      ...hd,
      LOCAL_STACK_PERSIST_DIR: PERSIST,
      LOCAL_STACK_CMS_PORT: String(PORTS.cms),
    });
  }
  console.log(
    "[stack] cms    no `dev:local` script in Unified CMS — plain wrangler dev --local (see docs/local-stack.md)",
  );
  const cmsWrangler = path.join(CMS_DIR, "node_modules", "wrangler", "bin", "wrangler.js");
  return start("cms", CMS_DIR, process.execPath, [cmsWrangler, ...devArgs(PORTS.cms, INSPECTOR.cms)], hd);
}

function start(name, cwd, exe, args, extraEnv = {}) {
  const env = {
    ...process.env,
    WRANGLER_REGISTRY_PATH: REGISTRY,
    WRANGLER_SEND_METRICS: "false",
    NO_COLOR: "1",
  };
  // Only the strings this script verified may reach wrangler -> a stray shell export can never pick the DB
  for (const k of Object.keys(env)) {
    if (
      k.startsWith("CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_") ||
      k.startsWith("WRANGLER_HYPERDRIVE_")
    ) {
      delete env[k];
    }
  }
  Object.assign(env, extraEnv);
  const log = fs.openSync(path.join(LOGS, `${name}.log`), "w");
  const isShell = args.length === 0;
  const child = spawn(exe, args, {
    cwd,
    env,
    detached: true,
    shell: isShell,
    stdio: ["ignore", log, log],
    windowsHide: true,
  });
  child.unref();
  return child.pid;
}

async function waitReady(name, seconds = 120) {
  const file = path.join(LOGS, `${name}.log`);
  for (let i = 0; i < seconds * 2; i++) {
    const text = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : "";
    // The CMS's dev:local keeps wrangler's output off our log file, so an open port also counts as ready
    if (/Ready on http/i.test(text) || (await portBusy(PORTS[name]))) return true;
    if (/\bERROR\b|EADDRINUSE/.test(text) && i > 10) return false;
    await sleep(500);
  }
  return false;
}

function adbReverse() {
  const devices = spawnSync("adb", ["devices"], { encoding: "utf8" });
  if (devices.status !== 0) {
    console.log(
      "[adb] adb not on PATH — run `adb reverse tcp:8787 tcp:8787` and `adb reverse tcp:8788 tcp:8788` yourself",
    );
    return;
  }
  const attached = devices.stdout.split("\n").filter((l) => /\tdevice\s*$/.test(l));
  if (attached.length === 0) {
    console.log("[adb] no device attached — plug the phone in, then re-run `up` or the two reverses by hand");
    return;
  }
  if (attached.length > 1 && !process.env.ANDROID_SERIAL) {
    console.log("[adb] more than one device — export ANDROID_SERIAL=<serial> and re-run `up`");
    return;
  }
  for (const port of [PORTS.worker, PORTS.cdn]) {
    const r = spawnSync("adb", ["reverse", `tcp:${port}`, `tcp:${port}`], { encoding: "utf8" });
    console.log(`[adb] reverse tcp:${port} -> ${r.status === 0 ? "ok" : (r.stderr || r.stdout).trim()}`);
  }
}

async function status() {
  const state = readState();
  if (state) {
    const live = Object.entries(state.pids).map(([n, p]) => `${n}:${alive(p) ? "running" : "dead"}`);
    console.log(`[status] started ${state.started_at} · ${live.join(" · ")}`);
  } else {
    console.log("[status] no stack.json — not started by this tool");
  }
  await probe("worker /me (expect 401)", `${WORKER_URL}/me`, (r) => r.status === 401);
  await probe(
    "cdn catalog/version.json",
    `${CDN_URL}/catalog/version.json`,
    (r) => r.status === 200,
    async (r) => `${r.headers.get("x-local-cdn")} ${(await r.text()).trim()}`,
  );
  await probe(
    "cdn catalog/statuses/all_1.json",
    `${CDN_URL}/catalog/statuses/all_1.json`,
    (r) => r.status === 200,
    async (r) => {
      const j = await r.json().catch(() => null);
      return `${r.headers.get("x-local-cdn")} items=${j?.total ?? "?"}`;
    },
  );
  if (state?.pids?.cms)
    await probe("cms /admin", `http://127.0.0.1:${PORTS.cms}/admin`, (r) => r.status < 500);
  const rev = spawnSync("adb", ["reverse", "--list"], { encoding: "utf8" });
  if (rev.status === 0)
    console.log(`[adb] reverse --list: ${rev.stdout.trim().replace(/\r?\n/g, " | ") || "(none)"}`);
}

async function probe(label, url, ok, detail) {
  try {
    const r = await fetch(url, { redirect: "manual", signal: AbortSignal.timeout(15_000) });
    const extra = detail ? await detail(r) : "";
    console.log(`[health] ${ok(r) ? "OK  " : "FAIL"} ${label}: HTTP ${r.status} ${extra}`);
  } catch (err) {
    console.log(`[health] FAIL ${label}: ${err?.cause?.code ?? err?.message ?? err}`);
  }
}

function down() {
  const state = readState();
  if (!state) console.log("[stack] no stack.json — nothing this tool started");
  for (const [name, pid] of Object.entries(state?.pids ?? {})) {
    if (!alive(pid)) {
      console.log(`[stack] ${name} (pid ${pid}) already stopped`);
      continue;
    }
    const r =
      process.platform === "win32"
        ? spawnSync("taskkill", ["/PID", String(pid), "/T", "/F"], { encoding: "utf8" })
        : spawnSync("kill", ["-TERM", `-${pid}`], { encoding: "utf8" });
    console.log(
      `[stack] stopped ${name} (pid ${pid})${r.status === 0 ? "" : ` — ${(r.stderr || "").trim()}`}`,
    );
  }
  if (state) fs.rmSync(STATE, { force: true });
  fs.rmSync(WORKER_ENV_FILE, { force: true });
  for (const port of [PORTS.worker, PORTS.cdn]) {
    spawnSync("adb", ["reverse", "--remove", `tcp:${port}`], { encoding: "utf8" });
  }
  console.log("[stack] down (local R2 state kept in the persist dir; delete it to start clean)");
}

/**
 * workers/.dev.vars + the CMS's ARUL_CATALOG_BUILD_SECRET as CATALOG_BUILD_SECRET, so a local CMS publish can
 * rebuild the local catalog. `--env-file` REPLACES .dev.vars rather than layering on it, hence the full copy;
 * a secret never rides argv (.claude/rules/scripts.md). The file lives in the git-ignored persist dir; `down` drops it.
 */
function writeWorkerEnv(withCms) {
  const lines = fs.readFileSync(path.join(WORKERS_DIR, ".dev.vars"), "utf8").split("\n");
  const cmsSecret = withCms ? readDotenv(path.join(CMS_DIR, ".dev.vars")).ARUL_CATALOG_BUILD_SECRET : "";
  const out = cmsSecret
    ? [
        ...lines.filter((l) => !l.trim().startsWith("CATALOG_BUILD_SECRET=")),
        `CATALOG_BUILD_SECRET=${cmsSecret}`,
      ]
    : lines;
  fs.mkdirSync(path.dirname(WORKER_ENV_FILE), { recursive: true });
  fs.writeFileSync(WORKER_ENV_FILE, out.join("\n") + "\n", { mode: 0o600 });
  console.log(
    `[stack] worker env ${cmsSecret ? "= .dev.vars + the CMS build secret" : "= .dev.vars"} (${WORKER_ENV_FILE})`,
  );
}

function readState() {
  try {
    return JSON.parse(fs.readFileSync(STATE, "utf8"));
  } catch {
    return null;
  }
}

function alive(pid) {
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

function portBusy(port) {
  return new Promise((resolve) => {
    const s = net.connect({ host: "127.0.0.1", port });
    s.once("connect", () => {
      s.destroy();
      resolve(true);
    });
    s.once("error", () => resolve(false));
  });
}

function readDotenv(file) {
  const out = {};
  if (!fs.existsSync(file)) return out;
  for (const raw of fs.readFileSync(file, "utf8").split("\n")) {
    const line = raw.trim();
    const eq = line.indexOf("=");
    if (!line || line.startsWith("#") || eq < 0) continue;
    let v = line.slice(eq + 1).trim();
    if (v.startsWith('"') || v.startsWith("'")) v = v.slice(1, -1);
    out[line.slice(0, eq).trim()] = v;
  }
  return out;
}
