// Generates `test/l10n/support/arb_index.g.dart` — the reverse map the l10n
// matrix uses to attribute a rendered string back to the ARB key it came from.
//
// It is generated rather than read at runtime because Layer 2 runs ON THE
// DEVICE, where `lib/app/l10n/*.arb` is not on disk. One committed table serves
// both layers, so the two can never disagree about what a string is.
//
// REGENERATE after any ARB edit — a translation fix, a demotion, a new key:
//
//     dart run tools/l10n/gen_arb_index.dart && dart format test/l10n/support
//
// The matrix asserts the table is in sync with the ARBs it can see (Layer 1
// only), so a forgotten run fails the suite instead of mis-attributing.

import 'dart:convert';
import 'dart:io';

const _locales = ['en', 'ta', 'te', 'kn', 'ml', 'hi'];
const _arbDir = 'lib/app/l10n';
const _out = 'test/l10n/support/arb_index.g.dart';

void main() {
  final byLocale = <String, Map<String, String>>{};
  final placeholders = <String, List<String>>{};

  for (final locale in _locales) {
    final file = File('$_arbDir/app_$locale.arb');
    if (!file.existsSync()) {
      stderr.writeln('missing ${file.path}');
      exit(1);
    }
    final json = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
    final strings = <String, String>{};
    for (final entry in json.entries) {
      if (entry.key.startsWith('@')) {
        // Metadata: only the template ARB carries placeholder declarations.
        if (locale == 'en' &&
            entry.key.startsWith('@') &&
            entry.key.length > 1) {
          final meta = entry.value;
          if (meta is Map && meta['placeholders'] is Map) {
            placeholders[entry.key.substring(1)] = (meta['placeholders'] as Map)
                .keys
                .cast<String>()
                .toList();
          }
        }
        continue;
      }
      final value = entry.value;
      if (value is String) strings[entry.key] = value;
    }
    byLocale[locale] = strings;
  }

  final buf = StringBuffer()
    ..writeln('// GENERATED by tools/l10n/gen_arb_index.dart — do not edit.')
    ..writeln('//')
    ..writeln('// Regenerate after ANY ARB change:')
    ..writeln('//     dart run tools/l10n/gen_arb_index.dart')
    ..writeln()
    ..writeln('/// Every localized string, by locale then by ARB key.')
    ..writeln('///')
    ..writeln(
      '/// A locale map is SHORTER than English when keys have been demoted to',
    )
    ..writeln(
      '/// English-everywhere: a demoted key is absent from the five non-English',
    )
    ..writeln(
      '/// ARBs, and gen_l10n back-fills the template value at runtime.',
    )
    ..writeln('library;')
    ..writeln()
    ..writeln('const Map<String, Map<String, String>> kArbStrings = {');
  for (final locale in _locales) {
    buf.writeln("  '$locale': {");
    final strings = byLocale[locale]!;
    for (final key in strings.keys) {
      buf.writeln("    '$key': ${_literal(strings[key]!)},");
    }
    buf.writeln('  },');
  }
  buf
    ..writeln('};')
    ..writeln()
    ..writeln(
      '/// Keys whose message takes ICU placeholders, with their names.',
    )
    ..writeln(
      '/// Their rendered text never equals the template, so the matrix',
    )
    ..writeln('/// matches them by turning the template into a regex.')
    ..writeln('const Map<String, List<String>> kArbPlaceholders = {');
  final placeholderKeys = placeholders.keys.toList()..sort();
  for (final key in placeholderKeys) {
    final names = placeholders[key]!.map((n) => "'$n'").join(', ');
    buf.writeln("  '$key': [$names],");
  }
  buf.writeln('};');

  File(_out)
    ..createSync(recursive: true)
    ..writeAsStringSync(buf.toString());

  final total = byLocale['en']!.length;
  stdout.writeln('$_out written');
  stdout.writeln('  en: $total keys');
  for (final locale in _locales.skip(1)) {
    final n = byLocale[locale]!.length;
    stdout.writeln(
      '  $locale: $n keys${n == total ? '' : '  (${total - n} demoted)'}',
    );
  }
  stdout.writeln('  ${placeholders.length} parameterized keys');
}

/// A Dart single-quoted literal. Escapes what would otherwise break the file or
/// silently change the string: backslash, quote, `$`, and real newlines (which
/// several messages carry).
String _literal(String s) {
  final escaped = s
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$')
      .replaceAll('\n', r'\n')
      .replaceAll('\r', r'\r');
  return "'$escaped'";
}
