// Turns the recorded English matrix run into the subtraction set the permanent
// suite uses.
//
// §3 of the runbook defines a translation-induced finding as one that fires in
// some locale but NOT in the English baseline of the identical screen, state
// and configuration. That is a set difference, so it should be computed, not
// hand-maintained: a hand-written allowlist drifts, and every entry it gets
// wrong silently converts a real overflow into a "known defect".
//
// Regenerate:
//
//     L10N_ONLY=en L10N_AUDIT_OUT=build/l10n_audit \
//         flutter test test/l10n/l10n_matrix_test.dart
//     dart run tools/l10n/gen_english_baseline.dart
//
// (The first command is expected to FAIL — it is recording the defects, not
// asserting their absence. The second is what makes the suite green on them.)

import 'dart:convert';
import 'dart:io';

/// `A RenderFlex overflowed by 16 pixels on the bottom.`
({double px, String side})? _parseOverflow(String message) {
  final m = RegExp(
    r'overflowed by ([\d.]+) pixels on the (\w+)',
  ).firstMatch(message);
  if (m == null) return null;
  return (px: double.parse(m.group(1)!), side: m.group(2)!);
}

const _in = 'build/l10n_audit/layer1-en.json';
const _out = 'test/l10n/support/english_baseline.g.dart';

void main() {
  final file = File(_in);
  if (!file.existsSync()) {
    stderr.writeln(
      'missing $_in — run the en matrix with L10N_AUDIT_OUT first',
    );
    exit(1);
  }
  final json = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
  final findings = (json['findings'] as List).cast<Map<String, dynamic>>();

  // A signature is deliberately (kind, screen, config, key): the same string in
  // the same slot at the same size. Config is part of it because English
  // "Continue with Google" truncates at 320dp and fits at 360dp — a Tamil
  // truncation at 360dp is therefore translation-induced and must NOT be
  // subtracted. Overflow findings carry no key and match on the frame alone.
  final signatures = <String>{};
  // Overflows are kept separately, WITH their magnitude.
  //
  // An overflow finding carries no key, so its signature collapses to
  // kind|screen|config — and subtracting on that alone exempts the whole
  // screen at that configuration in every locale, at ANY size. A Malayalam
  // string pushing the language sheet 240px past the bottom would have matched
  // English's 16px and been swallowed. So the baseline records how far English
  // overflowed, and only an overflow no worse than that is subtracted.
  final overflowPx = <String, double>{};
  for (final f in findings) {
    if (f['kind'] == 'headroom') continue;
    if (f['kind'] == 'overflow') {
      final parsed = _parseOverflow(f['text'] as String? ?? '');
      if (parsed != null) {
        final key = '${f['screen']}|${f['config']}|${parsed.side}';
        final existing = overflowPx[key];
        if (existing == null || parsed.px > existing) {
          overflowPx[key] = parsed.px;
        }
      }
      continue;
    }
    signatures.add(
      [f['kind'], f['screen'], f['config'], f['key'] ?? ''].join('|'),
    );
  }

  final sorted = signatures.toList()..sort();
  final buf = StringBuffer()
    ..writeln('// GENERATED by tools/l10n/gen_english_baseline.dart.')
    ..writeln('//')
    ..writeln(
      '// The English baseline: every finding the matrix produces on the',
    )
    ..writeln('// SAME screens in `en`. These are layout defects and designed')
    ..writeln(
      '// truncations — demoting a translation cannot fix a slot that is',
    )
    ..writeln(
      '// too small for English either (OVERNIGHT-L10N.md §3), so they are',
    )
    ..writeln('// subtracted from every locale before the suite asserts.')
    ..writeln('//')
    ..writeln('// They are NOT dismissed: they are the morning punch list in')
    ..writeln('// docs/known-issues.md.')
    ..writeln('library;')
    ..writeln()
    ..writeln('/// `kind|screen|config|key` for each English finding.')
    ..writeln('const Set<String> kEnglishBaseline = <String>{');
  for (final s in sorted) {
    buf.writeln("  '$s',");
  }
  buf
    ..writeln('};')
    ..writeln()
    ..writeln('/// How far English overflowed, by `screen|config|side`.')
    ..writeln('///')
    ..writeln('/// A locale overflow is subtracted only when it is no WORSE')
    ..writeln('/// than English at the same frame. Anything larger is')
    ..writeln('/// translation-induced, however small English\'s own overflow.')
    ..writeln(
      'const Map<String, double> kEnglishOverflowPx = <String, double>{',
    );
  final overflowKeys = overflowPx.keys.toList()..sort();
  for (final k in overflowKeys) {
    buf.writeln("  '$k': ${overflowPx[k]},");
  }
  buf.writeln('};');

  File(_out).writeAsStringSync(buf.toString());
  stdout.writeln('  ${overflowPx.length} English overflow frames recorded');
  stdout.writeln('$_out written — ${sorted.length} baseline signatures');
  for (final s in sorted) {
    stdout.writeln('  $s');
  }
}
