// GENERATED by tools/l10n/gen_english_baseline.dart.
//
// The English baseline: every finding the matrix produces on the
// SAME screens in `en`. These are layout defects and designed
// truncations — demoting a translation cannot fix a slot that is
// too small for English either (OVERNIGHT-L10N.md §3), so they are
// subtracted from every locale before the suite asserts.
//
// They are NOT dismissed: they are the morning punch list in
// docs/known-issues.md.
library;

/// `kind|screen|config|key` for each English finding.
const Set<String> kEnglishBaseline = <String>{
  'truncated|refer.screen|320x569@1.3|referShareWhatsapp',
  'truncated|settings.screen|320x569@1.3|settingsFallbackEmail',
  'truncated|signin.screen|320x569@1.0|signInGoogle',
  'truncated|signin.screen|320x569@1.3|signInGoogle',
  'truncated|signin.screen|360x640@1.3|signInGoogle',
};

/// How far English overflowed, by `screen|config|side`.
///
/// A locale overflow is subtracted only when it is no WORSE
/// than English at the same frame. Anything larger is
/// translation-induced, however small English's own overflow.
const Map<String, double> kEnglishOverflowPx = <String, double>{
  'settings.language_sheet|320x569@1.0|bottom': 16.0,
  'settings.language_sheet|320x569@1.3|bottom': 28.0,
  'settings.language_sheet|360x640@1.0|bottom': 7.5,
  'settings.language_sheet|360x640@1.3|bottom': 19.0,
  'upload.screen|320x569@1.3|right': 29.0,
};
