// GENERATED by tools/l10n/gen_english_baseline.dart.
//
// The English baseline: every finding the matrix produces on the
// SAME screens in `en`. These are layout defects and designed
// truncations — demoting a translation cannot fix a slot that is
// too small for English either (OVERNIGHT-L10N.md §3), so they are
// subtracted from every locale before the suite asserts.
//
// They are NOT dismissed: they are the morning punch list in
// docs/known-issues.md.
library;

/// `kind|screen|config|key` for each English finding.
const Set<String> kEnglishBaseline = <String>{
  'truncated|settings.screen|320x569@1.3|settingsFallbackEmail',
};

/// How far English overflowed, by `screen|config|side`.
///
/// A locale overflow is subtracted only when it is no WORSE
/// than English at the same frame. Anything larger is
/// translation-induced, however small English's own overflow.
const Map<String, double> kEnglishOverflowPx = <String, double>{};
